# Generated by Django 3.0.7 on 2020-07-01 17:15

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phonebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('ContactNumber', models.CharField(blank=True, max_length=100)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('Image', models.ImageField(blank=True, default='', null=True, upload_to=api.models.upload_path)),
                ('IsDeleted', models.BooleanField(default=False)),
            ],
        ),
    ]
