# Generated by Django 3.0.7 on 2020-07-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200702_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebook',
            name='BirthDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
