# Generated by Django 3.0.7 on 2020-07-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200703_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebook',
            name='Image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
