# Generated by Django 3.0.7 on 2020-07-03 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200704_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonebook',
            name='IsDeleted',
        ),
    ]
